### ISSUE TITLE
from chemml import wrapperRUN

### ISSUE THREAD

**Issue by mirzanejad** [hachmannlab/chemml#5]
Hi, 

When I tried  "from chemml import wrapperRUN" in The Jupyter interpreter, I get the following error message: 

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-12-1a90844c7193> in <module>
----> 1 from chemml import wrapperRUN

ImportError: cannot import name 'wrapperRUN' from 'chemml' (/Users/amir/.local/lib/python3.8/site-packages/chemml/__init__.py)

---------------------------------------------------------------------------

How can resolve this issue? 

Thanks, 
Amir

**Comment by aditya1707** [comment]
As mentioned in the documentation [here](https://hachmannlab.github.io/chemml/CMLWTutorial.html), the ChemML Wrapper GUI works with an [older version of ChemML (0.4)](https://pypi.org/project/chemml/0.4.3/). We are working towards getting this up and running for the current version as well.
